baseURL = "https://k-explorer.github.io/blog/"
languageCode = "en-us"
title = "The DS Dev"
theme = "hyde"
[params]
  description = "Data Science can change the world"
[Menus]
  main = [
      {Name = "Tags", URL = "/tags"},
      {Name = "GitHub", URL = "https://github.com/k-explorer"},
      {Name = "RSS Feed", URL = "/index.xml"}
  ]
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      tabWidth = 4
      noClasses = false
      style = 'colorful'
